import mongoose from "mongoose";

const userSchema = new mongoose.Schema({
  username: {
    type: String,
    required: true,
    unique: true,
  },
  email: {
    type: String,
    required: true,
    unique: true,
  },
  password: {
    type: String,
    required: true,
  },
  
}, { timestamps: true });
//time of creation of the user and time of update of the user is generated by this timestamps object we can use this info to sort the things

const User = mongoose.model("User", userSchema);
//we can use the  crud operation using these models else we cannot perform the crud operation
export default User;